package com.gapps.myfm.search_data.model

import com.google.gson.annotations.SerializedName

data class PlayerDBResponse(
    @field:SerializedName("inf") val info: String,
    @field:SerializedName("secposition") val secposition: String,
    @field:SerializedName("wage") val wage: String,
    @field:SerializedName("weight") val weight: String,
    @field:SerializedName("position") val position: String,
    @field:SerializedName("uid") val uid: Long,
    @field:SerializedName("personality") val personality: String,
    @field:SerializedName("expires") val expires: String,
    @field:SerializedName("acc") val acceleration: Long,
    @field:SerializedName("wor") val workRate: Long,
    @field:SerializedName("vis") val vision: Long,
    @field:SerializedName("thr") val throwing: Long,
    @field:SerializedName("tec") val technique: Long,
    @field:SerializedName("tea") val teamwork: Long,
    @field:SerializedName("tck") val tackling: Long,
    @field:SerializedName("str") val strenght: Long,
    @field:SerializedName("sta") val stamina: Long,
    @field:SerializedName("tro") val rushingOut: Long,
    @field:SerializedName("ref") val reflexes: Long,
    @field:SerializedName("pun") val punching: Long,
    @field:SerializedName("pos") val positioning: Long,
    @field:SerializedName("pen") val penaltyTaking: Long,
    @field:SerializedName("pas") val passing: Long,
    @field:SerializedName("pac") val pace: Long,
    @field:SerializedName("1v1") val oneOnOnes: Long,
    @field:SerializedName("otb") val offTheBall: Long,
    @field:SerializedName("nat") val naturalFitness: Long,
    @field:SerializedName("mar") val marking: Long,
    @field:SerializedName("l th") val longThrows: Long,
    @field:SerializedName("lon") val longShots: Long,
    @field:SerializedName("ldr") val leadership: Long,
    @field:SerializedName("kic") val kicking: Long,
    @field:SerializedName("jum") val flair: Long,
    @field:SerializedName("hea") val heading: Long,
    @field:SerializedName("han") val handling: Long,
    @field:SerializedName("fre") val freeKickTacking: Long,
    @field:SerializedName("fla") val jumpingReach: Long,
    @field:SerializedName("fir") val firstTouch: Long,
    @field:SerializedName("fin") val finishing: Long,
    @field:SerializedName("ecc") val eccentricity: Long,
    @field:SerializedName("dri") val dribbling: Long,
    @field:SerializedName("det") val determination: Long,
    @field:SerializedName("dec") val decisions: Long,
    @field:SerializedName("cro") val crossing: Long,
    @field:SerializedName("cor") val corners: Long,
    @field:SerializedName("cnt") val concentration: Long,
    @field:SerializedName("cmp") val composure: Long,
    @field:SerializedName("com") val communication: Long,
    @field:SerializedName("cmd") val commandOfArea: Long,
    @field:SerializedName("bra") val bravery: Long,
    @field:SerializedName("bal") val balance: Long,
    @field:SerializedName("ant") val anticipation: Long,
    @field:SerializedName("agi") val agility: Long,
    @field:SerializedName("agg") val aggression: Long,
    @field:SerializedName("aer") val aerialReach: Long,
    @field:SerializedName("age") val age: Long,
    @field:SerializedName("name") val name: String,
    @field:SerializedName("transfer value") val price: String,
    @field:SerializedName("height") val height: String,
    @field:SerializedName("rec") val rec: String,
) {
    constructor() : this(
        "",
        "",
        "",
        "",
        "",
        0L,
        "",
        "",
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        0L,
        "",
        "",
        "",
        ""
    )
}
